spring:
  application:
    name: subscriptions-manager

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: pg
    password: pg
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: public

server:
  shutdown: graceful